builds:
  - goos:
      - linux
      - darwin

brews:
  - tap:
      owner: USERNAME
      name: homebrew-formulas
    folder: formula
    homepage: "https://github.com/USERNAME/PROJECT_NAME"
    description: "DESCRIPTION"
    commit_author:
      name: USERNAME
      email: USERNAME@example.com
